### ISSUE TITLE
Running tests / benchmarks fails due to missing hardcoded data files

### ISSUE THREAD

**Issue by mtnking** [Teque5/caf_cookoff#2]
Recommend adding the example data files to the repository and adjusting the hard-coded paths to point to them so that "cargo test" and "cargo +nightly bench" can work as documented.

**Comment by Teque5** [comment]
If you look at the `README.md`, the relative path locations for the data files are generated by executing `cd utils; python3 generate.py`, which will write all the FM chirps used by Rust/Go/Python implementations into the `data/` directory.
