### ISSUE TITLE
fftw flag capitalization

### ISSUE THREAD

**Issue by mtnking** [Teque5/caf_cookoff#3]
After a cargo update

  --> src/caf/xcor_fftw.rs:33:40
   |
33 |             &[n], Sign::Forward, Flag::Measure).unwrap();
   |                                        ^^^^^^^ associated item not found in `Flag`

MEASURE is in all caps now in fftw to conform to Rust naming conventions

**Comment by Teque5** [comment]
Thank you, issue fixed.
